easy_admin:
    site_name: "My Movies List"
    entities:
        User:
            class: App\Entity\User
            list:
                fields: ['id', 'email', 'name','roles']
            form:
                fields:
                    - name
                    - email
                    - { property: 'Password', type: 'text', type_options: { required: false } }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'User': 'ROLE_USER', 'Admin': 'ROLE_ADMIN', 'Ban user' : 'ROLE_BANNED' } } }
            design:
                    brand_color: '#1ABC9C'

        